language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - bash build_qt_static.sh

script:
  - bash configure.sh
  - cd build/
  - /usr/local/Qt-5.10.0/bin/qmake .. 
  - make -j$(nproc)

after_success:
  - curl --upload-file AppImageUpdater https://transfer.sh/AppImageUpdater
  - # wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - # bash upload.sh AppImage*.AppImage *zsync
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
