language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y # Change Open ssl before changing this
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd build/
  - cmake ..
  - make -j$(nproc)
  - mkdir -p appdir/usr/bin ; strip AppImageUpdater ; cp AppImageUpdater ./appdir/usr/bin/
  - mkdir -p appdir/usr/share/applications ; cp ../*.desktop ./appdir/usr/share/applications/
  - mkdir -p appdir/usr/lib/ ; cp /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 ./appdir/usr/lib/
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ ; cp ../*png appdir/usr/share/icons/hicolor/256x256/apps/AppImageUpdater.png
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD)
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage 

after_success:
  - wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - bash upload.sh AppImageUpdater*.AppImage *zsync
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
